# Dataset

# Data Preparation

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
import plotly.express as px
# from plotly.subplots import make_subplots
# import plotly.graph_objects as go 
import chardet
import warnings
warnings.filterwarnings("ignore")

import os
for dirname, _, filenames in os.walk("./dataset/"):
    for filename in filenames:
        print(os.path.join(dirname, filename))

./dataset/shopping_trends_updated.csv

In [2]:
with open("./dataset/shopping_trends_updated.csv", "rb") as f:
    print(chardet.detect(f.read()))

{'encoding': 'ascii', 'confidence': 1.0, 'language': ''}

In [3]:
df = pd.read_csv("./dataset/shopping_trends_updated.csv")

In [4]:
df

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3900 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [6]:
df.isna().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

# Data Understanding

In [8]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.749949,25.351538
std,1125.977353,15.207589,23.685392,0.716223,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.700000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [9]:
df.describe(include="object")

,Gender,Item Purchased,Category,Location,Size,Color,Season,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Payment Method,Frequency of Purchases
count,3900,3900,3900,3900,3900,3900,3900,3900,3900,3900,3900,3900,3900
unique,2,25,4,50,4,25,4,2,6,2,2,6,7
top,Male,Blouse,Clothing,Montana,M,Olive,Spring,No,Free Shipping,No,No,PayPal,Every 3 Months
freq,2652,171,1737,96,1755,177,999,2847,675,2223,2223,677,584

In [10]:
summary = pd.DataFrame({
    "Metric": [
        "Total Transaksi",
        "Total Amount",
        "Rata rata Amount per Transaksi",
        "Jumlah Location",
        "Jumlah Kategori Produk",
        "Jumlah Size",
        "Jumlah Pilihan Warna",
        "Jumlah Jenis Pengiriman",
        "Jumlah Payment"
    ],
    "Value": [
        df["Customer ID"].count(),
        df["Purchase Amount (USD)"].sum(),
        df["Purchase Amount (USD)"].mean(),
        df["Location"].nunique(),
        df["Category"].nunique(),
        df["Size"].nunique(),
        df["Color"].nunique(),
        df["Shipping Type"].nunique(),
        df["Payment Method"].nunique()
    ]
})

summary["Value"] = summary["Value"].apply(
    lambda x: round(x, 2) if isinstance(x, (int, float)) else x
)

summary

                           Metric      Value
0                 Total Transaksi    3900.00
1                    Total Amount  233081.00
2  Rata rata Amount per Transaksi      59.76
3                 Jumlah Location      50.00
4          Jumlah Kategori Produk       4.00
5                     Jumlah Size       4.00
6            Jumlah Pilihan Warna      25.00
7         Jumlah Jenis Pengiriman       6.00
8                  Jumlah Payment       6.00

## Amount Analysis

In [11]:
df["Purchase Amount (USD)"].describe()

count    3900.000000
mean       59.764359
std        23.685392
min        20.000000
25%        39.000000
50%        60.000000
75%        81.000000
max       100.000000
Name: Purchase Amount (USD), dtype: float64

In [12]:
fig = px.histogram(
    df["Purchase Amount (USD)"],
    nbins=50
)

fig.update_traces(
    marker_line_width=1,
    marker_line_color="black"
)

fig.show()

In [13]:
fig = px.box(
    df["Purchase Amount (USD)"]
)

fig.show()

**Insight:**
- Berdasarkan histogram, distribusi nilai Purchase Amount terlihat cukup merata pada rentang 20–100 USD tanpa adanya lonjakan ekstrem pada nilai tertentu.
- Hal ini juga didukung oleh boxplot yang menunjukkan tidak adanya outlier, sehingga distribusi transaksi dapat dikatakan relatif stabil dan tidak didominasi oleh transaksi dengan nilai yang terlalu tinggi maupun terlalu rendah.
- Selain itu, median amount berada di sekitar 60 USD, dengan 50% transaksi berada pada rentang 39–81 USD, menunjukkan bahwa sebagian besar customer melakukan transaksi pada nilai pembelian menengah.

# Exploratory Data Analysis

In [14]:
# df.to_excel("EDA - Customer Shopping Analysis.xlsx", index=False)

In [15]:
# file_path = r".\EDA - Customer Shopping Analysis.xlsx"
# os.system(f'start excel "{file_path}"')

# Dashboard